Feature/enhancement
Glympse/terraform-provider-nifi pull request #10
Opened 2017-10-02 14:41 UTC by af6140

* new resrouces, user, group, funnel, remote process group, port
* connection resource dealing with port/funnel
* support https client cert auth.

2017-10-03 22:45 UTC, egorpushkin commented
@af6140 Very cool stuff! We are looking into it and get back to you with comments soon.

2017-10-05 22:04 UTC, egorpushkin requested changes
Overall looks very good!
Please address comments.

2017-10-05 22:04 UTC, egorpushkin commented on README.md
> +Tip: how to ignore poisition changes in application
Lets move under `docs/tips.md` and refer to it in Documentation section below.

2017-10-05 22:04 UTC, egorpushkin commented on glide.yaml
> +package: github.com/af6140/terraform-provider-nifi
This needs to be reverted back to `glympse` in order for it to be merged.

2017-10-05 22:04 UTC, egorpushkin commented on install.sh
> +   nifi = "$GOPATH/src/github.com/af6140/terraform-provider-nifi/bin/local/terraforn-provider-nifi"
This needs to be reverted back to `glympse` in order for it to be merged.

2017-10-05 22:04 UTC, egorpushkin commented on main.go
> +	"github.com/af6140/terraform-provider-nifi/nifi"
This needs to be reverted back to `glympse` in order for it to be merged.

2017-10-05 22:04 UTC, egorpushkin commented on nifi/client.go
> +	HttpScheme string
I would recommend flipping those as the comment above refers to `Lock` rather than to `HttpScheme`.

2017-10-05 22:04 UTC, egorpushkin commented on nifi/client.go
> +	http_client := &http.Client{}
Lets use `httpClient`.

2017-10-05 22:04 UTC, egorpushkin commented on nifi/client.go
> +	log.Printf("[DEBUG]: http call error code: %d", response.StatusCode)
No need in `:`. Lets add URL to the message so it can be analyzed.

2017-10-05 22:04 UTC, egorpushkin commented on nifi/client.go
> +	// var buffer = new(bytes.Buffer)
Lets avoid checking in commented out snippets.

2017-10-05 22:04 UTC, egorpushkin commented on nifi/resource_connection.go
> +	//err = ConnectionStopProcessor(client, connection.Component.Source.Id)
Lets nuke the comment

2017-10-05 22:04 UTC, egorpushkin commented on nifi/resource_connection.go
> +	//err = ConnectionStopProcessor(client, connection.Component.Destination.Id)
Same regarding the comment

2017-10-05 22:05 UTC, egorpushkin commented
@tcolar PTAL if you get a chance.

2017-10-07 01:43 UTC, af6140 commented
Made changes according to comments.

2017-10-07 03:28 UTC, tcolar reviewed
Thanks for the PR. A bunch of comments but they are mostly the same idiomatic go type things a bunch of times.

2017-10-07 03:28 UTC, tcolar commented on nifi/client_extra_test.go
> +func TestClientUserCreate(t *testing.T) {
Yeah, tests !

2017-10-07 03:28 UTC, tcolar commented on nifi/client_test.go
> +				Properties:                       map[string]interface{}{},
@egorpushkin make sure your editor always run `gofmt` on save.

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_connection.go
>  	defer client.Lock.Unlock()
It's usually idiomatic to have the defer together with it's lock, ie: at line 144
```
client.Lock.Lock()
defer client.Lock.Lock()
```

On a related note, unless absolutely necessary the lock shouldn't be exported, meaning `lock` with a lowercase `l` so it may not be manipulated from outside the package. cc @egorpushkin

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +				//d.Set("name", d.Id())
Let's remove this comment too if not needed

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +	client := meta.(*Client)
should we do `client, ok := meta.(*Client)` and bail if not ok, or are we pretty certain meta may  only be a *client

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +	err := ResourceFunnelUpdateInternal(d, meta)
Move the `defer`(#94) here, the whole point of defer is to try to guarantee it happens, so `defer unlock` should be out as close to `lock` as possible.

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +	if err != nil {
more idiomatic to write it as such (return early and avoid nested ifs)
```
if "not_found" == err.Error() {
 			d.SetId("")
 			return nil
}
 if err != nil  {
 			return fmt.Errorf("Error retrieving Funnel: %s", funnelId)
 }
// rest of code
```

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +	log.Printf("[INFO] Deleting Funnel: %s...", d.Id())
defer here

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +	if err != nil {
same comment about uneeded nested ifs

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_funnel.go
> +		if "not_found" == err.Error() {
nested ifs

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +				//d.Set("name", d.Id())
remove if uneeded

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +	log.Printf("[INFO] Updating Group: %s..., not implemented", d.Id())
defer here

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +		if "not_found" == err.Error() {
nested ifs

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +	log.Printf("[INFO] Deleting Group: %s...", d.Id())
defer here

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +		if "not_found" == err.Error() {
nested ifs

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +		if nil != err {
nested ifs

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +				if nil != err {
very nested ifs :)

2017-10-07 03:28 UTC, tcolar commented on nifi/resource_group.go
> +				if nil != err {
most of those cases have `returns`, since returns are final, you can typically take out lany following else (it's `else` by definition) and cute down on the deep nesting.

2017-12-09 03:09 UTC, af6140 commented
Adddressed most comments.

2017-12-12 05:42 UTC, egorpushkin approved these changes

2017-12-12 05:43 UTC, egorpushkin commented
LGTM

@af6140 Thanks for your hard work on that!

2017-12-23 03:12 UTC, merged